### ISSUE TITLE
AE2 Spatial Dimension Generation Crash

### ISSUE THREAD

**Issue by Rongmario** [Barteks2x/CubicChunks#374]
https://gist.githubusercontent.com/Rongmario/aad9fa9e5286bf436744b06815f3d545/raw/512a1c2e95b9e0717c8bdd9a681632309b758e4e/gistfile1.txt

**Comment by Rongmario** [comment]
This was with the above setting in AE2's worldgen:

1. Disabled all ores (charged/normal certus quartz)
2. Disabled Chest Loot
3. Disabled Meteor Generation

**Comment by Archengius** [comment]
It's not a world generation crash, it's AE 2 spatial dimension generator crash.

**Comment by Rongmario** [comment]
Fixed title

**Comment by Shad0wlife** [comment]
For the record: this is a crash due to AE's very lazy ChunkGenerator code. For me it didn't crash, but on trying to move something to spatial dimension the same Error appeared.

Can be fixed by giving AE2 some proper chunk generator code.

Spatial storage still won't work with the fixed generation though. That would require some deep ExtendedBlockStorage black magic it seems.

**Comment by Niko-sk2x** [comment]
Since this doesn't appear to be fixable in CC, moving to compatibility reports and closing.
